name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout kód
      - name: Checkout code
        uses: actions/checkout@v2

      # JDK 17 beállítása
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build és tesztelés Maven-nel a megfelelő könyvtárban
      - name: Build with Maven
        run: mvn clean install
        working-directory: ./bookshopweb
